// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_proxy from "./routes/api/proxy.ts";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $HeroCarousel from "./islands/HeroCarousel.tsx";
import * as $ListCarousel from "./islands/ListCarousel.tsx";
import * as $ModalButton from "./islands/ModalButton.tsx";
import * as $Select from "./islands/Select.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/proxy.ts": $api_proxy,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/HeroCarousel.tsx": $HeroCarousel,
    "./islands/ListCarousel.tsx": $ListCarousel,
    "./islands/ModalButton.tsx": $ModalButton,
    "./islands/Select.tsx": $Select,
    "./islands/SignupForm.tsx": $SignupForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
